version: 2

# Build from the docs/ directory with Sphinx
sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

# Explicitly set the version of Python and its requirements
python:
    version: 3.9
    install:
        - requirements: dev-requirements.txt
        - method: pip
          path: .

formats:
    - pdf
